// To-do: Migrate each resource to seperate file


export let resources: Array<String> = ["Account",
    "AllergyIntolerance",
    "BodySite",
    "CarePlan",
    "Claim",
    "ClinicalImpression",
    "Communication",
    "CommunicationRequest",
    "Composition",
    "Condition",
    "Contract",
    "DetectedIssue",
    "Device",
    "DeviceUseRequest",
    "DeviceUseStatement",
    "DiagnosticOrder",
    "DiagnosticReport",
    "DocumentManifest",
    "DocumentReference",
    "Encounter",
    "EnrollmentRequest",
    "EpisodeOfCare",
    "FamilyMemberHistory",
    "Flag",
    "Goal",
    "ImagingObjectSelection",
    "ImagingStudy",
    "Immunization",
    "ImmunizationRecommendation",
    "List",
    "Media",
    "MedicationAdministration",
    "MedicationDispense",
    "MedicationOrder",
    "MedicationStatement",
    "NutritionOrder",
    "Observation",
    "Order",
    "Procedure",
    "ProcedureRequest",
    "QuestionnaireResponse",
    "ReferralRequest",
    "RelatedPerson",
    "RiskAssessment",
    "Specimen",
    "SupplyDelivery",
    "SupplyRequest",
    "VisionPrescription"
];

